# This is a basic workflow to help you get started with Actions

name: Build

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: install dependencies
        run: yarn install
      - name: test
        run: yarn test
      - name: Build
        run: export NODE_OPTIONS="--max-old-space-size=4096" && yarn build
